/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedCompanySlugRouteImport } from './routes/_authed/$companySlug'
import { Route as AuthedCompanySlugIndexRouteImport } from './routes/_authed/$companySlug/index'
import { Route as AuthedCompanySlugWarehouseRouteImport } from './routes/_authed/$companySlug/warehouse'
import { Route as AuthedCompanySlugSeasonsRouteImport } from './routes/_authed/$companySlug/seasons'
import { Route as AuthedCompanySlugFieldsRouteImport } from './routes/_authed/$companySlug/fields'
import { Route as AuthedCompanySlugFieldsFieldIdRouteImport } from './routes/_authed/$companySlug/fields/$fieldId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompanySlugRoute = AuthedCompanySlugRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompanySlugIndexRoute = AuthedCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCompanySlugRoute,
} as any)
const AuthedCompanySlugWarehouseRoute =
  AuthedCompanySlugWarehouseRouteImport.update({
    id: '/warehouse',
    path: '/warehouse',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugSeasonsRoute =
  AuthedCompanySlugSeasonsRouteImport.update({
    id: '/seasons',
    path: '/seasons',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugFieldsRoute = AuthedCompanySlugFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AuthedCompanySlugRoute,
} as any)
const AuthedCompanySlugFieldsFieldIdRoute =
  AuthedCompanySlugFieldsFieldIdRouteImport.update({
    id: '/$fieldId',
    path: '/$fieldId',
    getParentRoute: () => AuthedCompanySlugFieldsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/$companySlug': typeof AuthedCompanySlugRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AuthedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$companySlug/fields': typeof AuthedCompanySlugFieldsRouteWithChildren
  '/$companySlug/seasons': typeof AuthedCompanySlugSeasonsRoute
  '/$companySlug/warehouse': typeof AuthedCompanySlugWarehouseRoute
  '/$companySlug/': typeof AuthedCompanySlugIndexRoute
  '/$companySlug/fields/$fieldId': typeof AuthedCompanySlugFieldsFieldIdRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof AuthedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AuthedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$companySlug/fields': typeof AuthedCompanySlugFieldsRouteWithChildren
  '/$companySlug/seasons': typeof AuthedCompanySlugSeasonsRoute
  '/$companySlug/warehouse': typeof AuthedCompanySlugWarehouseRoute
  '/$companySlug': typeof AuthedCompanySlugIndexRoute
  '/$companySlug/fields/$fieldId': typeof AuthedCompanySlugFieldsFieldIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authed/$companySlug': typeof AuthedCompanySlugRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_authed/': typeof AuthedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authed/$companySlug/fields': typeof AuthedCompanySlugFieldsRouteWithChildren
  '/_authed/$companySlug/seasons': typeof AuthedCompanySlugSeasonsRoute
  '/_authed/$companySlug/warehouse': typeof AuthedCompanySlugWarehouseRoute
  '/_authed/$companySlug/': typeof AuthedCompanySlugIndexRoute
  '/_authed/$companySlug/fields/$fieldId': typeof AuthedCompanySlugFieldsFieldIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/$companySlug'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/auth/'
    | '/$companySlug/fields'
    | '/$companySlug/seasons'
    | '/$companySlug/warehouse'
    | '/$companySlug/'
    | '/$companySlug/fields/$fieldId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/auth'
    | '/$companySlug/fields'
    | '/$companySlug/seasons'
    | '/$companySlug/warehouse'
    | '/$companySlug'
    | '/$companySlug/fields/$fieldId'
  id:
    | '__root__'
    | '/_authed'
    | '/auth'
    | '/_authed/$companySlug'
    | '/_authed/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authed/'
    | '/auth/'
    | '/_authed/$companySlug/fields'
    | '/_authed/$companySlug/seasons'
    | '/_authed/$companySlug/warehouse'
    | '/_authed/$companySlug/'
    | '/_authed/$companySlug/fields/$fieldId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$companySlug': {
      id: '/_authed/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof AuthedCompanySlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$companySlug/': {
      id: '/_authed/$companySlug/'
      path: '/'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof AuthedCompanySlugIndexRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/warehouse': {
      id: '/_authed/$companySlug/warehouse'
      path: '/warehouse'
      fullPath: '/$companySlug/warehouse'
      preLoaderRoute: typeof AuthedCompanySlugWarehouseRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/seasons': {
      id: '/_authed/$companySlug/seasons'
      path: '/seasons'
      fullPath: '/$companySlug/seasons'
      preLoaderRoute: typeof AuthedCompanySlugSeasonsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/fields': {
      id: '/_authed/$companySlug/fields'
      path: '/fields'
      fullPath: '/$companySlug/fields'
      preLoaderRoute: typeof AuthedCompanySlugFieldsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/fields/$fieldId': {
      id: '/_authed/$companySlug/fields/$fieldId'
      path: '/$fieldId'
      fullPath: '/$companySlug/fields/$fieldId'
      preLoaderRoute: typeof AuthedCompanySlugFieldsFieldIdRouteImport
      parentRoute: typeof AuthedCompanySlugFieldsRoute
    }
  }
}

interface AuthedCompanySlugFieldsRouteChildren {
  AuthedCompanySlugFieldsFieldIdRoute: typeof AuthedCompanySlugFieldsFieldIdRoute
}

const AuthedCompanySlugFieldsRouteChildren: AuthedCompanySlugFieldsRouteChildren =
  {
    AuthedCompanySlugFieldsFieldIdRoute: AuthedCompanySlugFieldsFieldIdRoute,
  }

const AuthedCompanySlugFieldsRouteWithChildren =
  AuthedCompanySlugFieldsRoute._addFileChildren(
    AuthedCompanySlugFieldsRouteChildren,
  )

interface AuthedCompanySlugRouteChildren {
  AuthedCompanySlugFieldsRoute: typeof AuthedCompanySlugFieldsRouteWithChildren
  AuthedCompanySlugSeasonsRoute: typeof AuthedCompanySlugSeasonsRoute
  AuthedCompanySlugWarehouseRoute: typeof AuthedCompanySlugWarehouseRoute
  AuthedCompanySlugIndexRoute: typeof AuthedCompanySlugIndexRoute
}

const AuthedCompanySlugRouteChildren: AuthedCompanySlugRouteChildren = {
  AuthedCompanySlugFieldsRoute: AuthedCompanySlugFieldsRouteWithChildren,
  AuthedCompanySlugSeasonsRoute: AuthedCompanySlugSeasonsRoute,
  AuthedCompanySlugWarehouseRoute: AuthedCompanySlugWarehouseRoute,
  AuthedCompanySlugIndexRoute: AuthedCompanySlugIndexRoute,
}

const AuthedCompanySlugRouteWithChildren =
  AuthedCompanySlugRoute._addFileChildren(AuthedCompanySlugRouteChildren)

interface AuthedRouteChildren {
  AuthedCompanySlugRoute: typeof AuthedCompanySlugRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCompanySlugRoute: AuthedCompanySlugRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
