/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthedCompanySlugRouteImport } from './routes/_authed/$companySlug'
import { Route as AuthedCompanySlugIndexRouteImport } from './routes/_authed/$companySlug/index'
import { Route as AuthedCompanySlugWarehouseRouteImport } from './routes/_authed/$companySlug/warehouse'
import { Route as AuthedCompanySlugSeasonsRouteImport } from './routes/_authed/$companySlug/seasons'
import { Route as AuthedCompanySlugReportsRouteImport } from './routes/_authed/$companySlug/reports'
import { Route as AuthedCompanySlugOrganizationsRouteImport } from './routes/_authed/$companySlug/organizations'
import { Route as AuthedCompanySlugNotificationsRouteImport } from './routes/_authed/$companySlug/notifications'
import { Route as AuthedCompanySlugImportsExportsRouteImport } from './routes/_authed/$companySlug/imports-exports'
import { Route as AuthedCompanySlugFieldsRouteImport } from './routes/_authed/$companySlug/fields'
import { Route as AuthedCompanySlugFarmProfileRouteImport } from './routes/_authed/$companySlug/farm-profile'
import { Route as AuthedCompanySlugDiariesRouteImport } from './routes/_authed/$companySlug/diaries'
import { Route as AuthedCompanySlugCreditsRouteImport } from './routes/_authed/$companySlug/credits'
import { Route as AuthedCompanySlugAuditsRouteImport } from './routes/_authed/$companySlug/audits'
import { Route as AuthedCompanySlugActivitiesRouteImport } from './routes/_authed/$companySlug/activities'
import { Route as AuthedCompanySlugFieldsFieldIdRouteImport } from './routes/_authed/$companySlug/fields/$fieldId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedCompanySlugRoute = AuthedCompanySlugRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompanySlugIndexRoute = AuthedCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCompanySlugRoute,
} as any)
const AuthedCompanySlugWarehouseRoute =
  AuthedCompanySlugWarehouseRouteImport.update({
    id: '/warehouse',
    path: '/warehouse',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugSeasonsRoute =
  AuthedCompanySlugSeasonsRouteImport.update({
    id: '/seasons',
    path: '/seasons',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugReportsRoute =
  AuthedCompanySlugReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugOrganizationsRoute =
  AuthedCompanySlugOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugNotificationsRoute =
  AuthedCompanySlugNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugImportsExportsRoute =
  AuthedCompanySlugImportsExportsRouteImport.update({
    id: '/imports-exports',
    path: '/imports-exports',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugFieldsRoute = AuthedCompanySlugFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AuthedCompanySlugRoute,
} as any)
const AuthedCompanySlugFarmProfileRoute =
  AuthedCompanySlugFarmProfileRouteImport.update({
    id: '/farm-profile',
    path: '/farm-profile',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugDiariesRoute =
  AuthedCompanySlugDiariesRouteImport.update({
    id: '/diaries',
    path: '/diaries',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugCreditsRoute =
  AuthedCompanySlugCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugAuditsRoute = AuthedCompanySlugAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthedCompanySlugRoute,
} as any)
const AuthedCompanySlugActivitiesRoute =
  AuthedCompanySlugActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthedCompanySlugRoute,
  } as any)
const AuthedCompanySlugFieldsFieldIdRoute =
  AuthedCompanySlugFieldsFieldIdRouteImport.update({
    id: '/$fieldId',
    path: '/$fieldId',
    getParentRoute: () => AuthedCompanySlugFieldsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/$companySlug': typeof AuthedCompanySlugRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AuthedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$companySlug/activities': typeof AuthedCompanySlugActivitiesRoute
  '/$companySlug/audits': typeof AuthedCompanySlugAuditsRoute
  '/$companySlug/credits': typeof AuthedCompanySlugCreditsRoute
  '/$companySlug/diaries': typeof AuthedCompanySlugDiariesRoute
  '/$companySlug/farm-profile': typeof AuthedCompanySlugFarmProfileRoute
  '/$companySlug/fields': typeof AuthedCompanySlugFieldsRouteWithChildren
  '/$companySlug/imports-exports': typeof AuthedCompanySlugImportsExportsRoute
  '/$companySlug/notifications': typeof AuthedCompanySlugNotificationsRoute
  '/$companySlug/organizations': typeof AuthedCompanySlugOrganizationsRoute
  '/$companySlug/reports': typeof AuthedCompanySlugReportsRoute
  '/$companySlug/seasons': typeof AuthedCompanySlugSeasonsRoute
  '/$companySlug/warehouse': typeof AuthedCompanySlugWarehouseRoute
  '/$companySlug/': typeof AuthedCompanySlugIndexRoute
  '/$companySlug/fields/$fieldId': typeof AuthedCompanySlugFieldsFieldIdRoute
}
export interface FileRoutesByTo {
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AuthedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$companySlug/activities': typeof AuthedCompanySlugActivitiesRoute
  '/$companySlug/audits': typeof AuthedCompanySlugAuditsRoute
  '/$companySlug/credits': typeof AuthedCompanySlugCreditsRoute
  '/$companySlug/diaries': typeof AuthedCompanySlugDiariesRoute
  '/$companySlug/farm-profile': typeof AuthedCompanySlugFarmProfileRoute
  '/$companySlug/fields': typeof AuthedCompanySlugFieldsRouteWithChildren
  '/$companySlug/imports-exports': typeof AuthedCompanySlugImportsExportsRoute
  '/$companySlug/notifications': typeof AuthedCompanySlugNotificationsRoute
  '/$companySlug/organizations': typeof AuthedCompanySlugOrganizationsRoute
  '/$companySlug/reports': typeof AuthedCompanySlugReportsRoute
  '/$companySlug/seasons': typeof AuthedCompanySlugSeasonsRoute
  '/$companySlug/warehouse': typeof AuthedCompanySlugWarehouseRoute
  '/$companySlug': typeof AuthedCompanySlugIndexRoute
  '/$companySlug/fields/$fieldId': typeof AuthedCompanySlugFieldsFieldIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authed/$companySlug': typeof AuthedCompanySlugRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_authed/': typeof AuthedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authed/$companySlug/activities': typeof AuthedCompanySlugActivitiesRoute
  '/_authed/$companySlug/audits': typeof AuthedCompanySlugAuditsRoute
  '/_authed/$companySlug/credits': typeof AuthedCompanySlugCreditsRoute
  '/_authed/$companySlug/diaries': typeof AuthedCompanySlugDiariesRoute
  '/_authed/$companySlug/farm-profile': typeof AuthedCompanySlugFarmProfileRoute
  '/_authed/$companySlug/fields': typeof AuthedCompanySlugFieldsRouteWithChildren
  '/_authed/$companySlug/imports-exports': typeof AuthedCompanySlugImportsExportsRoute
  '/_authed/$companySlug/notifications': typeof AuthedCompanySlugNotificationsRoute
  '/_authed/$companySlug/organizations': typeof AuthedCompanySlugOrganizationsRoute
  '/_authed/$companySlug/reports': typeof AuthedCompanySlugReportsRoute
  '/_authed/$companySlug/seasons': typeof AuthedCompanySlugSeasonsRoute
  '/_authed/$companySlug/warehouse': typeof AuthedCompanySlugWarehouseRoute
  '/_authed/$companySlug/': typeof AuthedCompanySlugIndexRoute
  '/_authed/$companySlug/fields/$fieldId': typeof AuthedCompanySlugFieldsFieldIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/$companySlug'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/auth/'
    | '/$companySlug/activities'
    | '/$companySlug/audits'
    | '/$companySlug/credits'
    | '/$companySlug/diaries'
    | '/$companySlug/farm-profile'
    | '/$companySlug/fields'
    | '/$companySlug/imports-exports'
    | '/$companySlug/notifications'
    | '/$companySlug/organizations'
    | '/$companySlug/reports'
    | '/$companySlug/seasons'
    | '/$companySlug/warehouse'
    | '/$companySlug/'
    | '/$companySlug/fields/$fieldId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/auth'
    | '/$companySlug/activities'
    | '/$companySlug/audits'
    | '/$companySlug/credits'
    | '/$companySlug/diaries'
    | '/$companySlug/farm-profile'
    | '/$companySlug/fields'
    | '/$companySlug/imports-exports'
    | '/$companySlug/notifications'
    | '/$companySlug/organizations'
    | '/$companySlug/reports'
    | '/$companySlug/seasons'
    | '/$companySlug/warehouse'
    | '/$companySlug'
    | '/$companySlug/fields/$fieldId'
  id:
    | '__root__'
    | '/_authed'
    | '/auth'
    | '/_authed/$companySlug'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authed/'
    | '/auth/'
    | '/_authed/$companySlug/activities'
    | '/_authed/$companySlug/audits'
    | '/_authed/$companySlug/credits'
    | '/_authed/$companySlug/diaries'
    | '/_authed/$companySlug/farm-profile'
    | '/_authed/$companySlug/fields'
    | '/_authed/$companySlug/imports-exports'
    | '/_authed/$companySlug/notifications'
    | '/_authed/$companySlug/organizations'
    | '/_authed/$companySlug/reports'
    | '/_authed/$companySlug/seasons'
    | '/_authed/$companySlug/warehouse'
    | '/_authed/$companySlug/'
    | '/_authed/$companySlug/fields/$fieldId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/$companySlug': {
      id: '/_authed/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof AuthedCompanySlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$companySlug/': {
      id: '/_authed/$companySlug/'
      path: '/'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof AuthedCompanySlugIndexRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/warehouse': {
      id: '/_authed/$companySlug/warehouse'
      path: '/warehouse'
      fullPath: '/$companySlug/warehouse'
      preLoaderRoute: typeof AuthedCompanySlugWarehouseRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/seasons': {
      id: '/_authed/$companySlug/seasons'
      path: '/seasons'
      fullPath: '/$companySlug/seasons'
      preLoaderRoute: typeof AuthedCompanySlugSeasonsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/reports': {
      id: '/_authed/$companySlug/reports'
      path: '/reports'
      fullPath: '/$companySlug/reports'
      preLoaderRoute: typeof AuthedCompanySlugReportsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/organizations': {
      id: '/_authed/$companySlug/organizations'
      path: '/organizations'
      fullPath: '/$companySlug/organizations'
      preLoaderRoute: typeof AuthedCompanySlugOrganizationsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/notifications': {
      id: '/_authed/$companySlug/notifications'
      path: '/notifications'
      fullPath: '/$companySlug/notifications'
      preLoaderRoute: typeof AuthedCompanySlugNotificationsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/imports-exports': {
      id: '/_authed/$companySlug/imports-exports'
      path: '/imports-exports'
      fullPath: '/$companySlug/imports-exports'
      preLoaderRoute: typeof AuthedCompanySlugImportsExportsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/fields': {
      id: '/_authed/$companySlug/fields'
      path: '/fields'
      fullPath: '/$companySlug/fields'
      preLoaderRoute: typeof AuthedCompanySlugFieldsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/farm-profile': {
      id: '/_authed/$companySlug/farm-profile'
      path: '/farm-profile'
      fullPath: '/$companySlug/farm-profile'
      preLoaderRoute: typeof AuthedCompanySlugFarmProfileRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/diaries': {
      id: '/_authed/$companySlug/diaries'
      path: '/diaries'
      fullPath: '/$companySlug/diaries'
      preLoaderRoute: typeof AuthedCompanySlugDiariesRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/credits': {
      id: '/_authed/$companySlug/credits'
      path: '/credits'
      fullPath: '/$companySlug/credits'
      preLoaderRoute: typeof AuthedCompanySlugCreditsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/audits': {
      id: '/_authed/$companySlug/audits'
      path: '/audits'
      fullPath: '/$companySlug/audits'
      preLoaderRoute: typeof AuthedCompanySlugAuditsRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/activities': {
      id: '/_authed/$companySlug/activities'
      path: '/activities'
      fullPath: '/$companySlug/activities'
      preLoaderRoute: typeof AuthedCompanySlugActivitiesRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
    '/_authed/$companySlug/fields/$fieldId': {
      id: '/_authed/$companySlug/fields/$fieldId'
      path: '/$fieldId'
      fullPath: '/$companySlug/fields/$fieldId'
      preLoaderRoute: typeof AuthedCompanySlugFieldsFieldIdRouteImport
      parentRoute: typeof AuthedCompanySlugFieldsRoute
    }
  }
}

interface AuthedCompanySlugFieldsRouteChildren {
  AuthedCompanySlugFieldsFieldIdRoute: typeof AuthedCompanySlugFieldsFieldIdRoute
}

const AuthedCompanySlugFieldsRouteChildren: AuthedCompanySlugFieldsRouteChildren =
  {
    AuthedCompanySlugFieldsFieldIdRoute: AuthedCompanySlugFieldsFieldIdRoute,
  }

const AuthedCompanySlugFieldsRouteWithChildren =
  AuthedCompanySlugFieldsRoute._addFileChildren(
    AuthedCompanySlugFieldsRouteChildren,
  )

interface AuthedCompanySlugRouteChildren {
  AuthedCompanySlugActivitiesRoute: typeof AuthedCompanySlugActivitiesRoute
  AuthedCompanySlugAuditsRoute: typeof AuthedCompanySlugAuditsRoute
  AuthedCompanySlugCreditsRoute: typeof AuthedCompanySlugCreditsRoute
  AuthedCompanySlugDiariesRoute: typeof AuthedCompanySlugDiariesRoute
  AuthedCompanySlugFarmProfileRoute: typeof AuthedCompanySlugFarmProfileRoute
  AuthedCompanySlugFieldsRoute: typeof AuthedCompanySlugFieldsRouteWithChildren
  AuthedCompanySlugImportsExportsRoute: typeof AuthedCompanySlugImportsExportsRoute
  AuthedCompanySlugNotificationsRoute: typeof AuthedCompanySlugNotificationsRoute
  AuthedCompanySlugOrganizationsRoute: typeof AuthedCompanySlugOrganizationsRoute
  AuthedCompanySlugReportsRoute: typeof AuthedCompanySlugReportsRoute
  AuthedCompanySlugSeasonsRoute: typeof AuthedCompanySlugSeasonsRoute
  AuthedCompanySlugWarehouseRoute: typeof AuthedCompanySlugWarehouseRoute
  AuthedCompanySlugIndexRoute: typeof AuthedCompanySlugIndexRoute
}

const AuthedCompanySlugRouteChildren: AuthedCompanySlugRouteChildren = {
  AuthedCompanySlugActivitiesRoute: AuthedCompanySlugActivitiesRoute,
  AuthedCompanySlugAuditsRoute: AuthedCompanySlugAuditsRoute,
  AuthedCompanySlugCreditsRoute: AuthedCompanySlugCreditsRoute,
  AuthedCompanySlugDiariesRoute: AuthedCompanySlugDiariesRoute,
  AuthedCompanySlugFarmProfileRoute: AuthedCompanySlugFarmProfileRoute,
  AuthedCompanySlugFieldsRoute: AuthedCompanySlugFieldsRouteWithChildren,
  AuthedCompanySlugImportsExportsRoute: AuthedCompanySlugImportsExportsRoute,
  AuthedCompanySlugNotificationsRoute: AuthedCompanySlugNotificationsRoute,
  AuthedCompanySlugOrganizationsRoute: AuthedCompanySlugOrganizationsRoute,
  AuthedCompanySlugReportsRoute: AuthedCompanySlugReportsRoute,
  AuthedCompanySlugSeasonsRoute: AuthedCompanySlugSeasonsRoute,
  AuthedCompanySlugWarehouseRoute: AuthedCompanySlugWarehouseRoute,
  AuthedCompanySlugIndexRoute: AuthedCompanySlugIndexRoute,
}

const AuthedCompanySlugRouteWithChildren =
  AuthedCompanySlugRoute._addFileChildren(AuthedCompanySlugRouteChildren)

interface AuthedRouteChildren {
  AuthedCompanySlugRoute: typeof AuthedCompanySlugRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCompanySlugRoute: AuthedCompanySlugRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
